stages:
  - checks
  - test
  - deploy

pre-commit:
  stage: checks
  image: python:3.10-bookworm
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

pylint:
  stage: checks
  extends: .tox_setup
  image: python:3.10-bookworm
  script:
  - tox -e pylint

.tox_setup:
  before_script:
    - apt-get update
    - apt-get install redis-server -y
    - redis-server --daemonize yes
    - python -V
    - pip install tox

test-py311-dj42:
  extends: .tox_setup
  image: python:3.11-bookworm
  script:
    - tox -e py311-django42

deploy-pypi:
  stage: deploy
  image: python:3.10-bookworm
  before_script:
    - pip install twine wheel build
  script:
    - python -m build
    - twine upload dist/*
  only:
    - tags
